### ISSUE TITLE
Proper internal gear calculation

### ISSUE THREAD

**Issue by lhns** [NicoSchlueter/HelicalGear#12]
The current internal gear calculation I implemented is wrong. Maybe someone else knows how to do it.

**Comment by phossystems** [comment]
I have noticed that they are prone to interference. I avoided doing internal gears as I never felt like I understood their geometry. I found this quite helpful: 
https://www.sdp-si.com/resources/elements-of-metric-gear-technology/page3.php#Section5
Here is what I believe to be true (please correct me if I am wrong):
Internal gears are "just negatives" of normal gears except Addendum and Dedendum are swapped.
Internal gears need to be profile shifted to avoid interference.
The Involute class does not currently take profile shifts into account.

I am pretty sure we need to implement a profile shift coefficient into the involute tooth generation.
I am currently redoing the UI and have added manual Addendum and Dedendum support which might be enough to get somewhat usable internal gears in some situations. I hope to release the new UI in the next two days.

**Comment by lhns** [comment]
Yeah the 3D printed gear sets I am currently doing it is fine. I probably need to do a PR to invert the backlash on internal gears.
But it is not really suitable if you really need accurate internal gears.

**Comment by phossystems** [comment]
I have fixed the backlash on internal gears with the new UI. Sorry I am pretty bad at doing regular small commits and other bits aren’t working fully at this time. Hope to push something tomorrow, maybe create a development branch.
I will start asking around for a involute equation that takes profile shift into account. This should pretty much fix the problem.

**Comment by lhns** [comment]
Love the new version! I am no expert on gears but the internal gears look correct to me.

**Comment by phossystems** [comment]
Thanks!
While the internal gears are correct they are prone to interference since they have no profile shift. The ideal profile shift for an internal gear is actually dependent on the other gear meshing with it.
But having at least some should improve most cases. While I understand how profile shift is done on an actual gear cutting machine I can’t wrap my head around generating the correct tooth profile. The whole Involute class is a bit of a black box to me. Never really looked at how exactly it worked.
Should be good enough, just check for interference, I believe more teeth reduce the risk.
