### ISSUE TITLE
Adding the output of information about the geometry of the gear in the setting and advanced windows

### ISSUE THREAD

**Issue by Goodfeat** [NicoSchlueter/HelicalGear#25]
Hello, is it possible in your script to create gears so that the "info" item is displayed not in a separate tab, but in the "setting" and "advanced" tabs

I'm not good at python programming.

I tried to rewrite the script myself, but I can't display information in real time.

It looks like there is an error in the script that does not allow processing this information

gear = generateGear (args.inputs) is handled by an exception and doesn't seem to allow information to be updated when parameters change

Technically, I understand that it is possible to do this, since there are scripts that display information immediately when changing parameters

**Comment by phossystems** [comment]
It is absolutely possible to do this, and it seems you are quite close.
The problem you encountered is due to a Fusion360 API bug where args.inputs returns an incomplete subset of command inputs. A workaround is to use args.input.parentCommand.commandInputs instead.

Attached is a modified file that should satisfy your requirements and what lines have been changed.
Please note that this file is largely untested.

Hope this helps!

[infoInSettings.zip](https://github.com/NicoSchlueter/HelicalGearPlus/files/4974951/infoInSettings.zip)

**Comment by Goodfeat** [comment]
Great, I tried a new script

It seems to work well )

![image](https://user-images.githubusercontent.com/44455128/88450024-fb98e280-ce8e-11ea-914d-01713f72c9a3.png)

**Comment by Goodfeat** [comment]
Thank you for the work done
